name: Move CodeTree Files

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # ✅ push 권한을 주기 위해 꼭 필요

jobs:
  organize_codetree:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Move CodeTree folders into /코드트리 (덮어쓰기 보장)
      run: |
        mkdir -p 코드트리
        shopt -s dotglob
        for folder in $(find . -maxdepth 1 -type d -name "2*" ! -name ".git" ! -name "코드트리"); do
          folder_name=$(basename "$folder")
          mkdir -p "코드트리/$folder_name"
          # rsync 사용: 기존 내용 삭제하고 정확히 복사 → 덮어쓰기 가능
          rsync -a --delete "$folder"/ "코드트리/$folder_name/"
          rm -r "$folder" || true
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "자동으로 CodeTree 폴더로 정리됨" || echo "No changes to commit"
        git push
